on:
  schedule:
    - cron: "30 23 */2 * *"
  workflow_dispatch:

name: Dependabot

permissions:
  pull-requests: write
  issues: write
 # repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

